.TH basename 1 "2021-08-15"

.SH NAME
basename - return non-directory portion of a pathname

.SH SYNOPSIS
.SY basename
.I string
[\fIsuffix\fR]
.YS

.SH DESCRIPTION
The
.I
basename
utility prints the non-directory portion of a pathname.
It prints the actual file name, discarded from the directory-part of the path.
Optionally the
.I
basename
utility discards the leading
.I
suffix
of the
.I
string\fR.

.SH OPERANDS
The following operands are supported:
.PP
.I
string
.RE
.RS 5
A string.
.RE
.I
suffix
.RE
.RS 5
A string

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
