.TH cal 1 "2021-08-24"

.SH NAME
cal - print a calendar

.SH SYNOPSIS
.SY cal
.OP \fR[\fImonth\fR] year
.YS

.SH DESCRIPTION
The
.I
cal
utility prints a calendar to the standard output.

.SH OPERANDS
The following operands are supported:
.PP
.I month
.RE
.RS 5
A month to be display from 1 (January) to 12 (December).
.RE
.I year
.RE
.RS 5
A year to be displayed.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
