.TH chown 1 "2021-08-15"

.SH NAME
chown - change the file ownership

.SH SYNOPSIS
.SY chown
.OP -h
\fIowner\fR[:\fIgroup\fR]
.I file...
.YS

.SY chown
.B -R
.OP -H\fR|\fB-L\fR|\fB-P
\fIowner\fR[:\fIgroup\fR]
.I file...
.YS

.SH DESCRIPTION
The
.I
chown
utility sets the user ID of the file named by each
.I file
operand to the user ID specified by the
.I owner
operand.
If the option
.B -R
was used, the
.I chown
utility changes the ownership of directory trees.

.SH OPTIONS
.B -R
.RE
.RS 5
Recursively change file user and group IDs.
.RE
.B -h
.RE
.RS 5
If a file is of type symbolic link, the
.I chown
utility tries to change the ownership of the link.
.RE
.B -H
.RE
.RS 5
If the
.B -R
option is specified and a symbolic link referencing a directory is specified on the command line,
.I chown
changes the user ID (and group ID, if specified) of the directory referenced by the symbolic link
and all files in the file hierarchy below it.
.RE
.B -L
.RE
.RS 5
If the
.B -R
option is specified and a symbolic link referencing a directory is specified on the command line
or encountered during traversal of a file hierarchy,
.I chown
changes the user ID (and group ID, if specified) of the directory referenced by the symbolic link
and all files in the file hierarchy below it.
.RE
.B -P
.RE
.RS 5
If the
.B -R
option is specified and a symbolic link referencing a directory is specified on the command line
or encountered during traversal of a file hierarchy,
.I chown
changes the user ID (and group ID, if specified) of the symbolic link.

.SH OPERANDS
The following operands are supported:
.PP
.I owner\fR[:\fIgroup\fR]
.RE
.RS 5
A user ID and optional group ID to be assigned to \fIfile\fR.
.RE
.I file
.RE
.RS 5
A pathname of a file whose user ID is to be modified.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
