.TH clear 1 "2021-04-09"

.SH NAME
clear - clear screen

.SH SYNOPSIS
.SY clear
.YS

.SH DESCRIPTION
The
.I clear
utility clears the current terminal screen by sending a row of escape sequences.

.SH OPTIONS
None.

.SH OPERANDS
None.

.SH STDIN
Not used.

.SH STDOUT
An escape sequence is written to standard output, which clears the terminal screen.

.SH STDERR
The standard error is being used for diagnostic messages.

.SH INPUT FILES
None.

.SH OUTPUT FILES
None.

.SH EXIT STATUS
The following exit values are returned:
.PP
0
.RE
.RS 5
Successfull completion.
.RE
>0
.RE
.RS 5
An error occured.
