.TH clear 1 "2021-08-15"

.SH NAME
clear - clear screen

.SH SYNOPSIS
.SY clear
.YS

.SH DESCRIPTION
The
.I clear
utility clears the current terminal screen by sending a row of escape sequences.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.

