.TH date 1 "2021-08-15"

.SH NAME
date - print the date and time

.SH SYNOPSIS
.SY date
.OP -u
.OP +format
.YS

.SH DESCRIPTION
The
.I date
utility writes the date and time to standard output.

.SH OPTIONS
.B -u
.RE
.RS 5
Perform operations as if the
.I TZ
environement variable was set to the string "GMT0".
Otherwise
.I date
uses the timezone indicated by the
.I TZ
environement variable or the system default if that variable is unset or null.

.SH OPERANDS
.B +format
.RE
.RS 5
When the format is specified, each conversion operand is replaced in the standard output by its corresponding value.
All other characters are copied without change.
