.TH dirname 1 "2021-03-11"

.SH NAME
dirname - return directory portion of a pathname

.SH SYNOPSIS
.SY dirname
.I string
.YS

.SH DESCRIPTION
The
.I
dirname
utility prints the directory portion of a pathname.

.SH OPTIONS
None.

.SH OPERANDS
The following operands are be supported:
.PP
.I
string
.RE
.RS 5
A string.

.SH STDIN
Not used.

.SH STDOUT
The
.I
dirname
utility writes the resulting string followed by a <newline> character to the standard output.

.SH STDERR
The standard error is being used only for diagnostic messages.

.SH INPUT FILES
None.

.SH OUTPUT FILES
None.

.SH EXIT STATUS
The following exit values are returned:
.PP
0
.RE
.RS 5
Successfull completion.
.RE
>0
.RE
.RS 5
An error occured.
