.TH dirname 1 "2021-08-15"

.SH NAME
dirname - return directory portion of a pathname

.SH SYNOPSIS
.SY dirname
.I string
.YS

.SH DESCRIPTION
The
.I
dirname
utility prints the directory portion of a pathname.

.SH OPERANDS
The following operands are be supported:
.PP
.I
string
.RE
.RS 5
A string.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
