.TH false 1 "2021-03-11"

.SH NAME
false - return false value

.SH SYNOPSIS
.SY false
.YS

.SH DESCRIPTION
The
.I
false
utility returns with the exit code one.

.SH OPTIONS
None.

.SH OPERANDS
None.

.SH STDIN
Not used.

.SH STDOUT
Not used.

.SH STDERR
Not used.

.SH INPUT FILES
None.

.SH OUTPUT FILES
None.

.SH EXIT STATUS
One.
