.TH halt 1 "2021-08-15"

.SH NAME
halt - Halt the machine

.SH SYNOPSIS
.SY halt
.YS

.SH DESCRIPTION
The
.I halt
utility causes the machine to shutdown.
It does that by killing the init process.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
