.TH halt 1 "2021-04-09"

.SH NAME
halt - Halt the machine

.SH SYNOPSIS
.SY halt
.YS

.SH DESCRIPTION
The
.I halt
utility causes the machine to shutdown.
It does that by killing the init process.

.SH OPTIONS
None.

.SH OPERANDS
None.

.SH STDIN
Not used.

.SH STDOUT
Not used.

.SH STDERR
The standard error is being used only for diagnostic messages.

.SH INPUT FILES
None.

.SH OUTPUT FILES
None.

.SH EXIT STATUS
The following exit values are returned:
.PP
0
.RE
.RS 5
The machine is being successfully shut down.
.RE
>0
.RE
.RS 5
An error occured.

