.TH head 1 "2021-08-15"

.SH NAME
head - copy the first part of files

.SH SYNOPSIS
.SY head
.OP -n number
.OP file...
.YS

.SH DESCRIPTION
The
.I
head
utility copies its input files to the standard output,
ending the output for each file at a designated point.
.PP
Copying ends at the point in each input file indicated by the
.B
-n
.I
number
option.
The option-argument
.I
number
is measured in units of lines.

.SH OPTIONS
.B
-n
.I
number
.RE
.RS 5
The first
.I
number
lines of each input file will be copied to standard output.
The
.I
number
option-argument has to be a positive decimal integer.
.PP
When a file contains less than
.I
number
lines, it is copied to standard output entirely.
.PP
If no options are specified,
.I
head
acts if
.B
-n 10
has been specified.

.SH OPERANDS
The following operand is supported:
.PP
.I
file
.RE
.RS 5
A pathname of an input file. If no
.I
file
operands are specified, the standard input is being used. If a
.I
file
is '-', the
.I
head
utility reads from the standard input.
