.TH id 1 "2021-08-15"

.SH NAME
id - return user identity

.SH SYNOPSIS
.SY id
[\fIuser\fR]
.YS
.SY id
.B -G
.OP -n
[\fIuser\fR]
.YS
.SY id
.B -g
.OP -nr
[\fIuser\fR]
.YS
.SY id
.B -u
.OP -nr
[\fIuser\fR]
.YS


.SH DESCRIPTION
The
.I id
utility writes information about the given
.I user
to standard output.
If no
.I user
was specified, the
.I id
utility defaults to the current user.

.SH OPTIONS
.B -G
.RE
.RS 5
Output all different group IDs (effective, real and supplementary).
.RE
.B -g
.RE
.RS 5
Output only the effective group ID.
.RE
.B -n
.RE
.RS 5
Output the name instaed of the numeric ID.
.RE
.B -r
.RE
.RS 5
Output the real ID instead of the effective ID.
.RE
.B -u
.RE
.RS 5
Output only the effective user ID.

.SH OPERANDS
.I user
.RE
.RS 5
The login name for which information is to be written.


.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
