.TH link 1 "2021-09-02"

.SH NAME
link - call link function

.SH SYNOPSIS
.SY link
.I file1
.I file2
.YS

.SH DESCRIPTION
The
.I link
utility calls the link() function with the parameters \fIfile1\fR and \fIfile2\fR.

.SH OPERANDS
The following operands are supported:
.PP
.I file1
.RE
.RS 5
The pathname of an existing file.
.RE
.I file2
.RE
.RS 5
The pathname of a new directory entry to be created.

.SH SEE ALSO
\fBlink\fR(2)

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
