.TH logname 1 "2021-09-02"

.SH NAME
logname - return user's login name

.SH SYNOPSIS
.SY logname
.YS

.SH DESCRIPTION
The
.I
logname
utility writes the user's login name to standard output.

.SH SEE ALSO
\fBgetlogin\fR(3)

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
