.TH mkdir 1 "2021-08-15"

.SH NAME
mkdir - make directories

.SH SYNOPSIS
.SY mkdir
.OP -p
.OP -m mode
.I
dir...
.YS

.SH DESCRIPTION
The
.I
mkdir
utility creates the directories specified by the operands, in the order specified.

.SH OPTIONS
.B
-m
.I
mode
.RE
.RS 5
Set the file permission bits of the newly-created directory to the specified
.I
mode
value.
.RE
.B
-p
.RE
.RS 5
Create any missing intermediate pathname components.
.PP
Each
.I
dir
operand that names an existing directory is ignored.

.SH OPERANDS
The following operands are supported:
.PP
.I
dir
.RE
.RS 5
A pathname of a directory to be created.
