.TH mv 1 "2021-08-15"

.SH NAME
mv - move files

.SH SYNOPSIS
.SY mv
.OP -if
.I source_file
.I target_file
.YS

.SY mv
.OP -if
.I source_file...
.I target_dir
.YS

.SH DESCRIPTION
The
.I
mv
utility moves files and directory structures.

.SH OPTIONS
.B -f
.RE
.RS 5
Do not prompt for confirmation if the destination path exists. Any previous occurence of the
.B -i
option is ignored.
.RE
.B -i
.RE
.RS 5
Prompt for confirmation if the destination path exists. Any previous occurence of the
.B -f
option is ignored.

.SH OPERANDS
The following operands are supported:
.PP
.I source_file
.RE
.RS 5
A pathname of a file or directory to be moved.
.RE
.I target_file
.RE
.RS 5
A new pathname of the file or directory to be moved.
.RE
.I target_dir
.RE
.RS 5
A pathname of an existing directory into which to move the input files.


.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
