.TH mv 1 "2021-04-10"

.SH NAME
mv - move files

.SH SYNOPSIS
.SY mv
.OP -if
.I source_file
.I target_file
.YS

.SY mv
.OP -if
.I source_file...
.I target_dir
.YS

.SH DESCRIPTION
The
.I
mv
utility moves files and directory structures.

.SH OPTIONS
.B -f
.RE
.RS 5
Do not prompt for confirmation if the destination path exists. Any previous occurence of the
.B -i
option is ignored.
.RE
.B -i
.RE
.RS 5
Prompt for confirmation if the destination path exists. Any previous occurence of the
.B -f
option is ignored.

.SH OPERANDS
The following operands are supported:
.PP
.I source_file
.RE
.RS 5
A pathname of a file or directory to be moved.
.RE
.I target_file
.RE
.RS 5
A new pathname of the file or directory to be moved.
.RE
.I target_dir
.RE
.RS 5
A pathname of an existing directory into which to move the input files.

.SH STDIN
The standard input is being used to read an input line in response to each prompt.

.SH STDOUT
Not used.

.SH STDERR
The prompts are written to standard error.
The standard error is also being used for diagnostic messages.

.SH INPUT FILES
The input files specified by each
.I source_file
operand can be of any type.

.SH OUTPUT FILES
The output files may be of any type.

.SH EXIT STATUS
The following exit values are returned:
.PP
0
.RE
.RS 5
Successfull completion.
.RE
>0
.RE
.RS 5
An error occured.
