.TH rm 1 "2021-08-15"

.SH NAME
rm - remove directory entries

.SH SYNOPSIS
.SY rm
.OP -iRr
.I
file...
.YS
.SY rm
.I -f
.OP -iRr
[\fIfile...\fR]

.SH DESCRIPTION
The
.I
rm
utility removes directory entries specified by the each
.I
file
operand, in the order specified.

.SH OPTIONS
.B -f
.RE
.RS 5
Do not prompt for confirmation. Do not write diagnostic messages or modify the exit status in the case of no file operands,
or in the case of operands that do not exist.
Any previous occurences of
.B -i
are ignored.
.RE
.B -i
.RE
.RS 5
Prompt for confirmation. Any previous occurences of
.B -f
are ignored.
.RE
.B -r
.RE
.RS 5
Remove file hierarchies.
.RE
.B -R
.RE
.RS 5
Same as \fB-r\fR.

.SH OPERANDS
The following operands are supported:
.PP
.I
file
.RE
.RS 5
A pathname of a directory entry to be removed.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
