.TH rmdir 1 "2021-08-15"

.SH NAME
rmdir - remove directories

.SH SYNOPSIS
.SY rmdir
.OP -p
.I
dir...
.YS

.SH DESCRIPTION
The
.I
rmdir
utility removes directory entries specified by the each
.I
dir
operands, in the order specified.
.PP
The directories are processed in the order specified.

.SH OPTIONS
.B
-p
.RE
.RS 5
Remove all directories in a pathname.

.SH OPERANDS
The following operands are supported:
.PP
.I
dir
.RE
.RS 5
A pathname of a directory to be removed.
