.TH rmdir 1 "2021-03-11"

.SH NAME
rmdir - remove directories

.SH SYNOPSIS
.SY rmdir
.OP -p
.I
dir...
.YS

.SH DESCRIPTION
The
.I
rmdir
utility removes directory entries specified by the each
.I
dir
operands, in the order specified.
.PP
The directories are processed in the order specified.

.SH OPTIONS
.B
-p
.RE
.RS 5
Remove all directories in a pathname.

.SH OPERANDS
The following operands are supported:
.PP
.I
dir
.RE
.RS 5
A pathname of a directory to be removed.

.SH STDIN
Not used.

.SH STDOUT
Not used.

.SH STDERR
The standard error is being used for diagnostic messages.

.SH INPUT FILES
None.

.SH OUTPUT FILES
None.

.SH EXIT STATUS
The following exit values shall be returned:
.PP
0
.RE
.RS 5
Successfull completion.
.RE
>0
.RE
.RS 5
An error occured.
