.TH sleep 1 "2021-08-15"

.SH NAME
sleep - suspend execution for an interval

.SH SYNOPSIS
.SY sleep
.I
time
.YS

.SH DESCRIPTION
The
.I
sleep
utility suspends execution for at least the integral number of seconds specified by the
.I
time
operand.

.SH OPERANDS
The following operand are be supported:
.PP
.I
time
.RE
.RS 5
A non-negative decimal integer specifying the number of seconds for which to suspend execution.
