.TH sync 1 "2021-08-15"

.SH NAME
sync - Write all changes to disk

.SH SYNOPSIS
.SY sync
.YS

.SH DESCRIPTION
The
.I
sync
utility invokes the UNIX
.I sync()
system call, which in turn writes all pending changes to disk.
The invokation of
.I
sync
is blocking.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
