.TH sync 1 "2021-04-09"

.SH NAME
sync - Write all changes to disk

.SH SYNOPSIS
.SY sync
.YS

.SH DESCRIPTION
The
.I
sync
utility invokes the UNIX
.I sync()
system call, which in turn writes all pending changes to disk.
The invokation of
.I
sync
is blocking.

.SH OPTIONS
None.

.SH OPERANDS
None.

.SH STDIN
Not used.

.SH STDOUT
Not used.

.SH STDERR
Not used.

.SH INPUT FILES
None.

.SH OUTPUT FILES
None.

.SH EXIT STATUS
Zero.
