.TH tee 1 "2021-08-15"

.SH NAME
tee - duplicate standard input

.SH SYNOPSIS
.SY tee
.OP -ai
[\fIfile\fR...]
.YS

.SH DESCRIPTION
The
.I
tee
utility copies standard input to standard output,
making a copy in zero or more files.
If the
.B
-a
option is specified
.I
tee
appends to
.I
file\fR.

.SH OPTIONS
.B
-a
.RE
.RS 5
Append the output to the files.
.RE
.B
-i
.RE
.RS 5
Ignore the
.I
SIGINT
signal.

.SH OPERANDS
The following operand is supported:
.PP
.I
file
.RE
.RS 5
A pathname of an output file.
If a
.I
file
is '-', it refers to a file named -
