.TH tr 1 "2021-08-15"

.SH NAME
tr - translate characters

.SH SYNOPSIS
.SY tr
.OP -c\fR|\fB-C
.OP -s
.I string1
.I string2
.YS
.SY tr
.B -s
.OP -c\fR|\fB-C
.I string1
.YS
.SY tr
.B -d
.OP -c\fR|\fB-C
.I string1
.YS
.SY tr
.B -ds
.OP -c\fR|\fB-C
.I string1
.I string2
.YS

.SH DESCRIPTION
The
.I
tr
utility copies the standard input to the standard output with substitution or deletion of selected characters.
The options specified and the
.I string1
and
.I string2
operands control translations that occur while copying characters.

.SH OPTIONS
.B -c
.RE
.RS 5
Complement the set of characters specified in
.I string1\fR.
.RE
.B -C
.RE
.RS 5
(same as -c)
.RE
.B -d
.RE
.RS 5
Delete all occurences of input characters that are specified by
.I string1\fR.
.RE
.B -s
.RE
.RS 5
Replace instances of repeated characters with a single character.

.SH OPERANDS
.B string1\fR,
.B string2
.RE
.RS 5
Translation control strings.
Each string represents a set of characters to be converted into an array of characters used for translation.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
