.TH true 1 "2021-03-11"

.SH NAME
true - return true value

.SH SYNOPSIS
.SY true
.YS

.SH DESCRIPTION
The
.I
true
utility returns with the exit code zero.

.SH OPTIONS
None.

.SH OPERANDS
None.

.SH STDIN
Not used.

.SH STDOUT
Not used.

.SH STDERR
Not used.

.SH INPUT FILES
None.

.SH OUTPUT FILES
None.

.SH EXIT STATUS
Zero.
