.TH true 1 "2021-08-15"

.SH NAME
true - return true value

.SH SYNOPSIS
.SY true
.YS

.SH DESCRIPTION
The
.I
true
utility returns with the exit code zero.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
