.TH tty 1 "2021-08-15"

.SH NAME
tty - print current physical terminal

.SH SYNOPSIS
.SY tty
.YS

.SH DESCRIPTION
The
.I tty
utility writes the path to the current physical terminal,
which normally resides in the
.I /dev/pts 
directory.


.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
