.TH tty 1 "2021-04-09"

.SH NAME
tty - print current physical terminal

.SH SYNOPSIS
.SY tty
.YS

.SH DESCRIPTION
The
.I tty
utility writes the path to the current physical terminal,
which normally resides in the
.I /dev/pts 
directory.

.SH OPTIONS
None.

.SH OPERANDS
None.

.SH STDIN
Not used.

.SH STDOUT
The path to the current physical terminal followed by a <newline>.

.SH STDERR
The standard error is being used for diagnostic messages.

.SH INPUT FILES
None.

.SH OUTPUT FILES
None.

.SH EXIT STATUS
The following exit values are returned:
.PP
0
.RE
.RS 5
Successfull completion.
.RE
>0
.RE
.RS 5
An error occured.
