.TH uname 1 "2021-08-15"

.SH NAME
uname - return UNIX name

.SH SYNOPSIS
.SY uname
.OP -amnrsv
.YS

.SH DESCRIPTION
By default the
.I
uname
utility writes the operating system name to standard output.
When options are specified, 
.I
uname
writes the specified information to standard output.

.SH OPTIONS
.B
-a
.RE
.RS 5
Behaves as though all of the options
.B
-mnrsv
were specified.
.RE
.B
-m
.RE
.RS 5
Write the name of the hardware type on which the system is running to standard output.
.RE
.B
-n
.RE
.RS 5
Write the hostname to standard output.
.RE
.B
-r
.RE
.RS 5
Write the current release level of the operating system implementation to standard output.
.RE
.B
-s
.RE
.RS 5
Write the name of the implementation of the operating system.
.RE
.B
-v
.RE
.RS 5
Write the current version level of this release of the operating system implementation to standard output.

.PP
.SH COPYRIGHT
.br
Copyright \(co 2021 Benjamin Stürz
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
