.TH unlink 1 "2021-08-15"

.SH NAME
unlink - call the unlink function

.SH SYNOPSIS
.SY unlink
.I
file
.YS

.SH DESCRIPTION
The
.I
unlink
utility performs the function call:
.RE
unlink(\fIfile\fR);
.PP
A used may need appropriate privileges to invoke the
.I
unlink
utility.

.SH OPERANDS
The following operands are supported:
.PP
.I
file
.RE
.RS 5
The pathname of an existing file.
